name: Repo Config Bootstrap

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello from Org-level workflow!"

